### ISSUE TITLE
Unable to load backends

### ISSUE THREAD

**Issue by kristopherdick-clc** [b1naryth1ef/piera#17]
Whether using your test hiera.yaml or my own hiera config, calling piera.Hiera() results in the following

```
piera/piera.py", line 106, in load
    if not len(obj):
TypeError: object of type 'filter' has no len()
```

wrapping the call to filter() in the list constructor seems to resolve the issue, a la
`obj = list(filter(lambda i: i.NAME == backend, backends))`

**Comment by MarvinXuya** [comment]
Im having the same issue

**Comment by b1naryth1ef** [comment]
This was an incompatibility with Python 3. The latest version (v1.1.0) should fix this.
