### ISSUE TITLE
Piera creates an `alias` block even when no aliases are specified.

### ISSUE THREAD

**Issue by mattikus** [b1naryth1ef/piera#4]
When no aliases are specified, piera will still create the configuration block, which raises the `jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: warning, bad_element: aliases, message: mgd: statement has no contents; ignored)` exception.

If no aliases are specified, it shouldn't output the block at all.

**Comment by b1naryth1ef** [comment]
I think you meant berry.
