### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by t2d** [b1naryth1ef/piera#7]
```
>>> import piera
>>> h = piera.Hiera("hiera.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/piera-1.0.0rc7-py2.7.egg/piera/piera.py", line 27, in __init__
    self.load(backends or [YAMLBackend, JSONBackend])
  File "/usr/local/lib/python2.7/dist-packages/piera-1.0.0rc7-py2.7.egg/piera/piera.py", line 75, in load
    self.get(None)
  File "/usr/local/lib/python2.7/dist-packages/piera-1.0.0rc7-py2.7.egg/piera/piera.py", line 230, in get
    path = os.path.join(self.base_path, backend.datadir.format(**ctx), path.format(**ctx))
IndexError: tuple index out of range
```

**Comment by b1naryth1ef** [comment]
Can you give an example of the hiera.yaml your trying to load?

**Comment by t2d** [comment]
---

:backends:
- yaml

:yaml:
  :datadir: "./hieradata"

:hierarchy:
- "node/%{::fqdn}"
- "node/%{::fqdn}-secret"
- common
- common-secret

:merge_behavior: deeper

**Comment by b1naryth1ef** [comment]
Your format key `%{::fqdn}` is breaking the path-formatting stuff as it's a reserved symbol inside Python formatting (see https://docs.python.org/2/library/string.html#grammar-token-format_spec). I would recommend renaming it, as I'm not sure there is really a great way to fix this sans using pure-regex to format the paths which seems kind of ugly.

**Comment by t2d** [comment]
But isn't that exactly, what the official documentation [0] proposes?

[0] https://docs.puppetlabs.com/hiera/3.0/hierarchy.html

**Comment by b1naryth1ef** [comment]
Good point, I was confused with the syntax of `%{::fqdn}`, but it's just the puppet-standard fully-qualified variable syntax. I just pushed a commit that should fix using FQ'd puppet variables, and I'll push out RC8 in a couple.

Thanks for reporting :)

**Comment by t2d** [comment]
Thank you, piera now reads the config without problems. Can you tell me how to access a host-specific var? I'm trying to use `h.get('puppetmaster', name='host.example.org')`, but just get the standard answer, not the one from `nodes/host.example.org.yaml`.

**Comment by b1naryth1ef** [comment]
Based upon your hiera.yaml above, wouldn't you want `h.get('puppetmaster', fqdn='host.example.org')`?

**Comment by t2d** [comment]
of course, you're right. thank you very much, great piece of software!
